invasives=[“Acer pseudoplatanus”,
“Achyranthes japonica”,
“Alliaria petiolata”,
“Ampelopsis brevipedunculata”,
“Anthriscus sylvestris”,
“Aralia elata”,
“Artemisia vulgaris”,
“Arthraxon hispidus”,
“Berberis thunbergii”,
“Brachypodium sylvaticum”,
“Cabomba caroliniana”,
“Cardamine impatiens”,
“Celastrus orbiculatus”,
“Centaurea stoebe”,
“Cirsium arvense”,
“Cynanchum louiseae”,
“Cynanchum rossicum”,
“Dioscorea polystachya”,
“Dipsacus laciniatus”,
“Egeria densa”,
“Elaeagnus umbellata”,
“Euphorbia cyparissias”,
“Euphorbia esula”,
“Ficaria verna”,
“Frangula alnus”,
“Glyceria maxima”,
“Heracleum mantegazzianum”,
“Humulus japonicus”,
“Hydrilla verticillata”,
“Hydrocharis morus-ranae”,
“Imperata cylindrica”,
“Iris pseudacorus”,
“Lepidium latifolium”,
“Lespedeza cuneata”,
“Ligustrum obtusifolium”,
“Lonicera japonica”,
“Lonicera maackii”,
“Lonicera morrowii”,
“Lonicera tatarica”,
“Lonicera x bella”,
“Ludwigia hexapetala”,
“Ludwigia peploides”,
“Lysimachia vulgaris”,
“Lythrum salicaria”,
“Microstegium vimineum”,
“Murdannia keisak”,
“Myriophyllum heterophyllum”,
“Myriophyllum heterophyllum x”,
“Myriophyllum spicatum”,
“Nymphoides peltata”,
“Oplismenus hirtellus”,
“Persicaria perfoliata”,
“(Polygonum perfoliatum)”,
“Phellodendron amurense”,
“Phragmites australis”,
“Phyllostachys aurea”,
“Phyllostachys aureosulcata”,
“Potamogeton crispus”,
“Pueraria montana Kudzu”
“Reynoutria japonica (Fallopia)”,
“japonica, Polygonum cuspidatum)”,
“Reynoutria sachalinensis”,
“Reynoutria x bohemica”,
“(Fallopia x bohemica, Polygonum x”,
“bohemica)
“Rhamnus cathartica”,
“Rosa multiflora”,
“Rubus phoenicolasius “,
“Salix atrocinerea”,
“Silphium perfoliatum”,
“Trapa natans”,
“Vitex rotundifolia”,
]
